name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      should_release:
        description: "Create release?"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MAPI
        run: |
            Invoke-WebRequest -Uri "https://files.catbox.moe/ut01ee.zip" -OutFile API.zip
            Expand-Archive -Path API.zip -DestinationPath API
            mkdir API\Mods
            Invoke-WebRequest -Uri "https://github.com/BadMagic100/HollowKnight.MagicUI/releases/download/v1.0.8057.41343/MagicUI.zip" -OutFile MagicUI.zip
            Expand-Archive -Path MagicUI.zip -DestinationPath "API\Mods\MagicUI"
            Invoke-WebRequest -Uri "https://github.com/homothetyhk/RandomizerMod/releases/download/v4.0.2/RandomizerMod.zip" -OutFile Rando.zip
            Expand-Archive -Path Rando.zip -DestinationPath "API\Mods\Randomizer 4"
            Invoke-WebRequest -Uri "https://github.com/homothetyhk/RandomizerCore/releases/download/v1.0.2/RandomizerCore.zip" -OutFile RandoCore.zip
            Expand-Archive -Path RandoCore.zip -DestinationPath "API\Mods\RandomizerCore"
            Invoke-WebRequest -Uri "https://github.com/homothetyhk/HollowKnight.ItemChanger/releases/download/v2.0.2/ItemChanger.zip" -OutFile IC.zip
            Expand-Archive -Path IC.zip -DestinationPath "API\Mods\ItemChanger"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Prepare artifacts for release
        uses: actions/upload-artifact@v2
        # only make a release if we manually request the build - other builds will be handled automatically with a push
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.should_release == 'true'
        with:
          name: Publish
          path: Rando4Stats/bin/Publish/RandoStats
  release:
    needs:
      - build
    runs-on: windows-latest
    # only make a release if we manually request the build - other builds will be handled automatically with a push
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.should_release == 'true'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Get build details
        id: details
        # this assumes that an MSBuild task that writes the SHA256 of the zip file to SHA.txt, and the mod version (for MagicUI,
        # this is the same as the assembly version) to version.txt. The contents of these files are read to step outputs for use in release
        run: |
          $sha = Get-Content artifacts/Publish/SHA.txt
          $ver = Get-Content artifacts/Publish/version.txt
          echo "::set-output name=archiveHash::$sha"
          echo "::set-output name=buildVersion::$ver"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: v${{ steps.details.outputs.buildVersion }}
          body: |
            SHA256: ${{ steps.details.outputs.archiveHash }}
          files: |
            artifacts/Publish/RandoStats.zip